# Regression test for lexer.star (todo.md P0 #1) -- runs lexer_dump.exe
# against fixtures/lexer_sample.nobasic and diffs its output against
# fixtures/lexer_sample.expected.txt, a dump generated once from the live
# Python reference (`compiler/lexer/lexer.py`) and frozen. Same "no
# in-language assertion facility, so dump and diff instead" shape
# `run_debugger_test.ps1` already established for `debugger.star` (see
# NOTES.md's "Testing" section) -- the format both dumps share (line:col,
# token-kind name, escaped lexeme, a fixed-2-decimal numeric-literal
# rendering, escaped string literal) is documented in `lexer_dump.star`'s
# own header comment.
#
# Usage: powershell -File projects/nova/NoBASIC/tests/run_lexer_test.ps1
# (rebuild lexer_dump.exe first if lexer.star/tokens.star changed -- see
# lexer_dump.star's own header comment for the build command.) Exits 0 on
# match, 1 otherwise.
#
# To regenerate fixtures/lexer_sample.expected.txt after a deliberate
# lexer.star change (only if the reference's own behavior also changed to
# match -- otherwise a diff here means a real regression, not a stale
# fixture): rerun the reference `Lexer` over
# fixtures/lexer_sample.nobasic with the same dump format and overwrite
# the file. There is no checked-in script for that half (it runs against
# the sibling Python project, not this one) -- see todo.md P0 #1's
# "Previous work" entry for the throwaway generator this fixture came from.

$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$novaBasicRoot = Split-Path -Parent $here
$dumper = Join-Path $here "lexer_dump.exe"
$sample = Join-Path $here "fixtures\lexer_sample.nobasic"
$expectedFile = Join-Path $here "fixtures\lexer_sample.expected.txt"

if (-not (Test-Path $dumper)) {
    Write-Error "lexer_dump.exe not found at $dumper -- build it first (see lexer_dump.star's own header comment for the build command)."
    exit 1
}

$actual = & $dumper $sample | Out-String
$expected = Get-Content $expectedFile -Raw

# Normalize line endings -- lexer_dump.exe's own `println` emits the host
# platform's line ending (CRLF on Windows); the checked-in fixture is
# plain LF (as generated by the Python reference script).
$actualNorm = $actual -replace "`r`n", "`n"
$expectedNorm = $expected -replace "`r`n", "`n"

if ($actualNorm.TrimEnd("`n") -eq $expectedNorm.TrimEnd("`n")) {
    Write-Host "PASS: lexer.star token dump matches $expectedFile"
    exit 0
} else {
    Write-Host "FAIL: lexer.star token dump differs from $expectedFile"
    $actualLines = $actualNorm -split "`n"
    $expectedLines = $expectedNorm -split "`n"
    Compare-Object $expectedLines $actualLines | Format-Table -AutoSize
    exit 1
}
