# Regression test for parser.star/ast.star (todo.md P0 #2) -- runs
# parser_dump.exe against fixtures/parser_sample.nobasic and diffs its
# output against fixtures/parser_sample.expected.txt, a dump generated once
# from the live Python reference (`compiler/parser/parser.py`) and frozen.
# Same "no in-language assertion facility, so dump and diff instead" shape
# `run_lexer_test.ps1` already established for the lexer -- see that
# script's own header comment and `parser_dump.star`'s for the dump format.
#
# Usage: powershell -File projects/nova/NoBASIC/tests/run_parser_test.ps1
# (rebuild parser_dump.exe first if parser.star/ast.star/lexer.star/
# tokens.star changed -- see parser_dump.star's own header comment for the
# build command.) Exits 0 on match, 1 otherwise.
#
# To regenerate fixtures/parser_sample.expected.txt after a deliberate
# parser.star/ast.star change (only if the reference's own behavior also
# changed to match -- otherwise a diff here means a real regression, not a
# stale fixture): rerun the reference `Parser` over
# fixtures/parser_sample.nobasic with the same dump format and overwrite
# the file. There is no checked-in script for that half (it runs against
# the sibling Python project, not this one) -- see todo.md P0 #2's
# "Previous work" entry for the throwaway generator this fixture came from.

$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$novaBasicRoot = Split-Path -Parent $here
$dumper = Join-Path $here "parser_dump.exe"
$sample = Join-Path $here "fixtures\parser_sample.nobasic"
$expectedFile = Join-Path $here "fixtures\parser_sample.expected.txt"

if (-not (Test-Path $dumper)) {
    Write-Error "parser_dump.exe not found at $dumper -- build it first (see parser_dump.star's own header comment for the build command)."
    exit 1
}

$actual = & $dumper $sample | Out-String
$expected = Get-Content $expectedFile -Raw

# Normalize line endings -- parser_dump.exe's own `println` emits the host
# platform's line ending (CRLF on Windows); the checked-in fixture is plain
# LF (as generated by the Python reference script).
$actualNorm = $actual -replace "`r`n", "`n"
$expectedNorm = $expected -replace "`r`n", "`n"

if ($actualNorm.TrimEnd("`n") -eq $expectedNorm.TrimEnd("`n")) {
    Write-Host "PASS: parser.star AST dump matches $expectedFile"
    exit 0
} else {
    Write-Host "FAIL: parser.star AST dump differs from $expectedFile"
    $actualLines = $actualNorm -split "`n"
    $expectedLines = $expectedNorm -split "`n"
    Compare-Object $expectedLines $actualLines | Format-Table -AutoSize
    exit 1
}
