# Heresy -- sprite art and sprite-buffer construction.
#
# Why this module exists: Star has no image/PNG loader builtin (the drawing
# surface is `draw_rect`/`draw_pixel`/`draw_pixels`/`texture_*` over raw RGBA
# `Bytes`), so the sprite PNGs sitting in `sprites/` are not loadable by the
# game itself. Rather than fight that, this module hand-authors every sprite
# as ASCII art in a top-level `const` multiline string -- one character per
# pixel, a legend mapping characters to RGBA colors -- and parses it at
# startup into a row-major RGBA `Bytes` buffer ready for `texture_update`/
# `texture_draw`. This is exactly how 90s shareware games shipped their
# art (as indexed pixel data, not compressed PNGs), and it keeps the art
# visible and editable as text, matching the level-map aesthetic in map.star.
#
# The `Bytes` buffers are built once at startup and cached in a `SpriteSet`
# struct; the game then uploads each into its own `texture_create` handle
# once and reuses it every frame via `texture_draw` (the cached-texture
# pattern `projects/nova/main.star` established -- no per-frame texture
# churn).

const SPRITE_W: i32 = 16
const SPRITE_H: i32 = 16

# Legend for sprite art:
#   '.'  transparent
#   'R'  red (imp body)
#   'r'  dark red (imp shading)
#   'Y'  yellow (imp eyes / starbolt core)
#   'O'  orange (starbolt glow)
#   'B'  brown (brute body)
#   'b'  dark brown (brute shading)
#   'W'  white (brute horns / eyes)
#   'G'  green (health vial)
#   'g'  dark green (health vial shading)
#   'C'  cyan (mana orb)
#   'c'  dark cyan (mana orb shading)
#   'M'  magenta (mana glow)

const IMP_ART: str = """................
................
......RRRR......
.....RRRRRR.....
....RRRRRRRR....
....rRRRRRRr....
....rRRRRRRr....
.....rRRRRr.....
......rRRr......
......rYYr......
......rYYr......
.......rr.......
......r..r......
.....r....r.....
................
................"""

const BRUTE_ART: str = """................
................
......BBBB......
.....BBBBBB.....
....BBBBBBBB....
....bBBBBBBb....
....bBBBBBBb....
.....bBBBBb.....
......bBBb......
......bWWb......
......bWWb......
.......bb.......
......b..b......
.....b....b.....
................
................"""

const HEALTH_ART: str = """................
................
................
................
......GGGG......
.....GGGGGG.....
....GGGGGGGG....
....gGGGGGGg....
....gGGGGGGg....
.....gGGGGg.....
......gGGg......
.......gg.......
................
................
................
................"""

const MANA_ART: str = """................
................
................
................
......CCCC......
.....CCCCCC.....
....CCCCCCCC....
....cCCCCCCc....
....cCCCCCCc....
.....cCCCCc.....
......cCCc......
.......cc.......
................
................
................
................"""

const STARBOLT_ART: str = """................
................
................
................
................
................
......OOOO......
.....OYYYYO.....
.....OYYYYO.....
......OOOO......
................
................
................
................
................
................"""

# RGBA color for a legend character. Returns (0,0,0,0) for transparent.
fn legend_color(ch: i32) -> (i32, i32, i32, i32):
    if ch == 82:
        return (200, 40, 40, 255)
    if ch == 114:
        return (120, 20, 20, 255)
    if ch == 89:
        return (240, 220, 60, 255)
    if ch == 79:
        return (240, 140, 40, 255)
    if ch == 66:
        return (120, 80, 50, 255)
    if ch == 98:
        return (70, 45, 30, 255)
    if ch == 87:
        return (240, 240, 240, 255)
    if ch == 71:
        return (60, 200, 60, 255)
    if ch == 103:
        return (30, 120, 30, 255)
    if ch == 67:
        return (60, 200, 200, 255)
    if ch == 99:
        return (30, 120, 120, 255)
    if ch == 77:
        return (200, 60, 200, 255)
    return (0, 0, 0, 0)

# Parse an ASCII-art sprite string into a row-major RGBA Bytes buffer.
fn parse_sprite(art: str) -> Bytes:
    let rows = str_split(art, "\n")
    let mut buf = Bytes()
    let mut y = 0
    while y < SPRITE_H:
        let row = rows[y]
        let row_bytes = bytes_from_str(row)
        let mut x = 0
        while x < SPRITE_W:
            let ch = (row_bytes[x] as i32)
            let c = legend_color(ch)
            buf.push(c.0 as u8)
            buf.push(c.1 as u8)
            buf.push(c.2 as u8)
            buf.push(c.3 as u8)
            x += 1
        y += 1
    return buf

struct SpriteSet:
    imp: Bytes
    brute: Bytes
    health: Bytes
    mana: Bytes
    starbolt: Bytes

fn make_sprites() -> SpriteSet:
    return SpriteSet(
        imp = parse_sprite(IMP_ART),
        brute = parse_sprite(BRUTE_ART),
        health = parse_sprite(HEALTH_ART),
        mana = parse_sprite(MANA_ART),
        starbolt = parse_sprite(STARBOLT_ART),
    )